#!/usr/bin/env perl
use strict;
use warnings;
use v5.10.0;

use Yum::Line;

my $line = Yum::Line->new_with_options;

my $command = shift;

if ($command eq 'list') {
	my $name = shift;

	printf '%-50s %-15s %-15s %-10s'."\n", qw(Name Version Release Arch);
	foreach my $package ($line->upstream($name)->packages) {
		printf '%-50s %-15s %-15s %-10s'."\n",
			$package->name,
			$package->version,
			$package->release,
			$package->arch;
	}
} elsif ($command eq 'rsync') {
	foreach my $name ($line->upstreams) {
		print "Synchronising upstream $name\n";
		$line->upstream($name)->rsync;
	}
} elsif ($command eq 'dump') {
	use Data::Dumper;
#$line->_upstream;
#warn Dumper($line);
	say 'Config file: ', $line->config_file;
	say 'Base';
#warn Dumper($line->base);
	say_base($line->base);

	say "\nUpstream Repositories";
	foreach my $name ($line->upstream_names) {
		say_repo($line->upstream($name));
	}

	say "\nTrain Repositories";
	foreach my $name ($line->train_names) {
		say_train($line->train($name));
	}
} else {
	die "must pass command\n";
}
exit 0;


sub say_base {
	my $base = shift;

	say '   Name ', $base->name;
	say '   Base ', $base->base;
	say '   Sync ', $base->sync;
	say '   Version ', $base->version;
	say '   Uses ', join (', ', @{ $base->_upstream_names });
	say '   Train';
	say "      $_->{name} $_->{version}" foreach ($base->train);
}

sub say_repo {
	my $repo = shift;

	say '   Name ', $repo->name;
	say $repo->sync
		? '      Sync '. $repo->sync_subbed
		: '      Local';
	say '      Directory ', $repo->directory;
	say '      Arch ', $repo->arch;
	say '      Rel ', $repo->rel;
	say '      Only Packages ', join (', ', $repo->restrict)
		if ($repo->restrict);
}

sub say_train {
	my $train = shift;

	say '   Name ', $train->name;
	say '      Base ', $train->base;
	say '      Uses ', join (', ', $train->upstream_names);
}
